# Generated by Django 4.0 on 2024-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
